### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [jogren/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
> Something to watch out for -- it looks like twice you used the word `foot` where you meant to put `food` 😂 Small typos like this can definitely bite you in programming! 
- [x] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The three attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The three methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [ ] The three attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [ ] The three methods I chose for **Class #2** represent behaviors or actions.
- [ ] I described what the methods do in **Class 2**.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [ ] The object I chose for **Class 2** is an instance of this class. 
- [ ] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [ ] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
> When you identify a class, make sure it is singular (for example, `Bottle` from our class example or `Book` or `Playlist`, etc.). It looks like your second class is trying to encompass multiple things, when a class should define the blueprint for *one* thing. Make two more files (class_3.txt and class_3_example_object.txt) and identify one more class from a restaurant (make sure it's singular) and one example of an object of that class. Add and commit those changes, then push back up to GitHub and let us know when you're ready for us to check it.
- [ ] Not Technical Ready
